// Gerado automaticamente via ClickUp API + Gemini em 17/08/2026 15:53:59
const lastUpdate = '17/08/2026 15:53:59';
const rawData = [
  {
    "id": "86ajqc9ph",
    "name": "[PRJ}-Criação Chamados na plataforma HALO (Portal Fast)",
    "status": "CRIANDO PPM",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "As áreas Tributária, Fiscal e Paralegal recebem diversas demandas de outros departamentos internos na Fast Shop com a necessidade de realizar ajustes em sistema, regularizações jurídicas, ajustes para liberações de documentos Fiscais, além rastreabilidade e eficiência dos atendimentos destes pedidos, podendo ser registrados em um único ambiente, garantindo maior controle dos prazos, definição de responsabilidades, histórico centralizado das interações e melhor visibilidade sobre o volume e status dos atendimentos.\nO portal reduzirá riscos de perda das informações com uma melhora de governança nos processos, facilitando a geração de indicadores de desempenho e proporcionando uma experiência mais ágil e transparente tanto para o solicitante quanto para a equipe fiscal.\n    \n",
    "ultimo_status": "Solicitada a elaboração do Documento Técnico (TD) para estruturação do fluxo de chamados fiscais e paralegais na plataforma HALO.\nO próximo passo consiste no desenho da solução para centralizar as demandas de e-mails e do sistema FCchamados, visando gerar indicadores da área.",
    "status_updated_at": "15/08/2026 17:00"
  },
  {
    "id": "86ajp65xa",
    "name": "[PRJ:DMND2148]-Reforma Tributária Devolução FinNfe= 4 DfeReferencia",
    "status": "EM HOMOLOGACAO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "Ago/2026",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "Com a reforma tributária são necessários ajustes nos processos de emissão de Notas Fiscais Eletrônicas. \nDe acordo com a publicação da NT_2025.002_v1.50, será necessário antecipar algumas funcionalidades previstas na PPM da Reforma Tributária em desenvolvimento, que passará a vigorar em ambiente de produção a partir de 05/10/2026. Uma delas é o referenciamento de chave origem a nível de item. Se não ocorrer a implementação as notas serão rejeitadas.\n    \n",
    "ultimo_status": "Demanda liberada para homologação sob responsabilidade de Ellen, após a conclusão e envio das evidências dos testes internos com sucesso.\nO cronograma oficial estabelece a fase de homologação de 10 a 14/08/2026, aprovação no CAB em 19/08/2026 e Go-Live em 25/08/2026.",
    "status_updated_at": "15/08/2026 22:56"
  },
  {
    "id": "86ajnr5t7",
    "name": "[PRJ]-Triangulação de Vendas",
    "status": "EM REUNIOES",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "Sem registros de justificativa, histórico de interações ou progresso documentados para a iniciativa até o momento.\nRecomenda-se a definição imediata do escopo estrutural e o alinhamento com os stakeholders para a realização do kick-off.",
    "status_updated_at": "03/08/2026 17:14"
  },
  {
    "id": "86ajn2bf9",
    "name": "[PRJ]- Migração para modelo de Split de Pagamento no Marketplace",
    "status": "EM REUNIOES",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "A minuta contratual e o plano de comunicação avançaram para revisão fiscal após parecer inicial do Jurídico sobre o novo fluxo de repasses.\nA análise dos impactos tributários foi agendada pela área Fiscal para após o fechamento de 13/07, com o projeto devidamente registrado no portfólio.",
    "status_updated_at": "15/08/2026 22:56"
  },
  {
    "id": "86ajn2519",
    "name": "[PRJ]-Venda produto Rua Q e Rua P",
    "status": "EM REUNIOES",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "Atividades atualmente suspensas devido à pendência de esclarecimentos cruciais por parte de Murata sobre as diretrizes do escopo.\nAguarda-se este alinhamento técnico para o desbloqueio das próximas etapas de execução e avanço da equipe.",
    "status_updated_at": "03/08/2026 17:14"
  },
  {
    "id": "86ajn24ga",
    "name": "[PRJ]-Venda de Sucata 63",
    "status": "EM REUNIOES",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "Fase de inicialização sem registro de interações ou detalhamento de justificativa no sistema até o momento.\nAguardam-se as definições preliminares de escopo e o alinhamento da equipe para o início das atividades.",
    "status_updated_at": "15/08/2026 16:28"
  },
  {
    "id": "86ajmpzkk",
    "name": "[PRJ]-Venda com entrega em Operador Logístico",
    "status": "ENVIADO AO REQUISITANTE",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "07/2026",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "A implementação do processo de Venda com entrega em Operador Logístico representa uma evolução estratégica para o canal B2B, ampliando significativamente a capacidade comercial da empresa sem a necessidade de aumento proporcional dos estoques ou da complexidade logística. Esse modelo permite que a empresa atue como fornecedora de mercadorias para parceiros comerciais que solicitam entrega diretamente em operadores logísticos como a operação Full do Mercado Livre e Amazon. Além de expandir o alcance comercial e possibilitar novos modelos de parceria, essa operação simplifica a operação logística da cadeia de suprimento, diminuindo custos de movimentação e armazenamento. Por se tratar de uma operação com requisitos fiscais e logísticos específicos, sua implantação exige a adequação de processos, sistemas e controles internos, garantindo conformidade tributária, rastreabilidade das operações e escalabilidade para suportar o crescimento futuro do canal B2B. \nBenefícios Esperados:\n• Expansão do alcance comercial; \n• Aumento do faturamento B2B sem ampliação relevante da estrutura;\n• Criação de novos modelos de negócio; \n• Maior competitividade e velocidade de atendimento. \n",
    "ultimo_status": "A proposta de projeto (PPM) com as premissas e os requisitos fiscais foi enviada ao requisitante em 27/07/2026 para análise.\nO projeto aguarda o retorno da área demandante para validação das condições propostas e posterior avanço no planejamento do fluxo logístico B2B.",
    "status_updated_at": "15/08/2026 22:56"
  },
  {
    "id": "86ajd31ab",
    "name": "[PRJ]-T-CIOT, NSTECH, PEF, MDF-e e CT-e",
    "status": "EM REUNIOES",
    "status_ppm": "PPM em Andamento",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "A ANTT vem ampliando os requisitos de controle das operações de transporte, desde maio de 2026 passou a exigir a emissão de: CIOT, PEF, MDF-e, e CT-e. O não atendimento dessas exigências pode ocasionar em autuações e multas. (R$252K/dia ou R$5.5MM/mês), porém a empresa não possui solução para emissão dos documentos, correndo risco de autuação.\nConsiderando o volume de operação da companhia, e a necessidade de garantir a conformidade legal e eficiência operacional, torna-se necessária a implantação de uma solução para automatizar e gerenciar, os documentos obrigatórios de transporte. Implantar uma plataforma que venha a atender as normativas vigentes e realizando automatização do processo.\n1.1 PROCESSO AS IS\nO processo de contratação e pagamento de fretes, consiste na gestão operacional e financeira, desde o envio da roteirização e execução das entregas, feito pelas transportadoras até o fechamento semanal dos valores de frete. As informações operacionais são consolidadas e validadas para cálculo dos pagamentos, permitindo a emissão de CT-es e faturas pelas transportadoras, porém no processo realizado hoje as transportadoras TAC EQUIPARADO: Não emite o MDFe por falta do CIOT e as transportadoras com mais de 3 veículos não possuem estrutura para emitir as documentações exigidas pela ANTT antes do carregamento. Após isso, o time de fretes analisa a conformidade dos documentos, aprovando-os para liquidação financeira ou encaminhando-os para ajustes quando são identificadas inconsistências. E o pagamento do frete é realizado para todas as transportadoras seja TAC equiparado e transportadoras com mais de 3 veículos via deposito em conta (TED) semanal, sendo que seria necessário para TAC EQUIPARADO pagamento via PEF\n",
    "ultimo_status": "Compartilhada a versão v7 do plano do projeto (PPM CIOT) e evidências associadas para validação do modelo de conformidade com a ANTT.\nO andamento atual concentra-se na revisão desta proposta para viabilizar a automação dos fluxos de pagamentos e emissão de documentos.",
    "status_updated_at": "15/08/2026 23:04"
  },
  {
    "id": "86ajc7q9w",
    "name": "[PRJ]-Crédito Extemporâneo PISCOFINS - Legado",
    "status": "T.I TRABALHANDO",
    "status_ppm": "Sem PPM",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "Geração de documentação solicitada pela EY para efetuar a refificação da EFD Contribuição de diversos periodos. Foi solicitado bases de contas contábeis, extraidas pelo SAP (Razão das contas contábeis em estrutura analitica).\n",
    "ultimo_status": "A base de dados do SAP foi gerada com sucesso pela TI e disponibilizada na plataforma Databricks.\nA pendência atual consiste no download dos dados pela área de negócios para envio subsequente à consultoria EY.",
    "status_updated_at": "17/08/2026 11:01"
  },
  {
    "id": "86ajc7hu3",
    "name": "[PRJ]-Exclusão do ICMS ST Antecipação nas Lojas de SP (Sangria 2)",
    "status": "AGUARDO SUBIDA PRODUCAO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "Ago/2026",
    "prazo": "07/2026",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": " A Diretoria Fiscal solicitou a criação de uma PPM para implementar a funcionalidade de não calcular o ICMS-ST nas remessas destinadas às lojas do Estado de São Paulo, quando a operação tiver origem na filial ES-Atacadista.\nAS IS\nAtualmente, em uma remessa de transferência da filial ES-Atacadista para qualquer loja localizada no Estado de São Paulo, há obrigatoriedade de recolhimento do ICMS-ST, seja por destaque na nota fiscal, seja por recolhimento na entrada da mercadoria no recebimento. Como não há protocolo firmado entre os Estados do Espírito Santo e de São Paulo, o recolhimento ocorre, em 100% dos casos, na entrada. Esse recolhimento aumenta o custo da mercadoria e impacta o fluxo de caixa. Posteriormente, a venda da mercadoria ocorre sem tributação de ICMS, uma vez que o recolhimento já foi realizado anteriormente.\nTO BE\nO objetivo do projeto é permitir que o sistema interprete essa operação como produto sem regra de ICMS-ST, sem a necessidade de remover ou alterar as regras tributárias dos produtos nos cadastros fiscais.\nEm junho de 2023, foi homologado o projeto “Sangria”, que realiza esse mesmo processo.\nNa ocasião, foram criadas telas de parametrização para vincular as filiais de origem e destino abrangidas pela funcionalidade. Essas telas foram desenvolvidas de forma parametrizável, permitindo novos cadastros conforme a necessidade dos usuários, sem configuração fixa em código. O projeto foi homologado e disponibilizado em produção; porém, em razão de alteração na malha fiscal, acabou não sendo utilizado.\nDessa forma, a presente solicitação já se encontra aproximadamente 80% concluída, restando apenas:\n·         Retestar integralmente o projeto para confirmar se a funcionalidade está 100% utilizável.\n·         Considerar um novo requisito para bloquear a transferência de mercadorias da filial 0063 e Filial 05 para as lojas, para os produtos cadastrados como “Sangria”.\n",
    "ultimo_status": "A homologação encontra-se suspensa devido a inconsistências identificadas nos testes recentes, demandando correções sistêmicas imediatas da equipe de desenvolvimento.\nO avanço do cronograma depende também da emissão do parecer jurídico sobre a coexistência tributária e da definição do CNPJ da Dark Store de Cajamar.",
    "status_updated_at": "17/08/2026 11:01"
  },
  {
    "id": "86ahw2uge",
    "name": "[PRJ]-Transportadora FSL Fast Shop Logistic",
    "status": "EM REUNIOES",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "Criação de uma Filial Logistica (Emissão de CTe)\n",
    "ultimo_status": "Documentação inicial (PPM e Business Case) estruturada, com o projeto atualmente focado no estudo de viabilidade pela área responsável para implantação de sistema de emissão de CTE em todos os processos.\nA modelagem operacional proposta prevê a utilização de certificado próprio da empresa, assemelhando-se ao fluxo de FBA para a consolidação logística.",
    "status_updated_at": "17/08/2026 11:02"
  },
  {
    "id": "86ahgemnb",
    "name": "[PRJ]-NUPAY",
    "status": "ENVIADO AO REQUISITANTE",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "A integração da carteira digital NuPay aguarda o retorno da área responsável quanto ao status de validação do requisito fiscal enviado.\nEsta indefinição sobre o andamento do processo fiscal constitui o principal ponto de atenção e risco para o cronograma do projeto.",
    "status_updated_at": "17/08/2026 15:53"
  },
  {
    "id": "86ahfje7y",
    "name": "[PRJ:]-Reforma Tributária - NFSe Nacional GAN Fase 2",
    "status": "T.I TRABALHANDO",
    "status_ppm": "PPM em Andamento",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "Projeto de reforma tributária da Nota Fiscal de Serviço NFS-e. Atendimento para destacar IBS e CBS na nota fiscal. emissão dos documentos.\n\n",
    "ultimo_status": "Apresentada a tela de simulação do serviço, o projeto avançou para a etapa de revisão dos ajustes acordados com a Neogrid.\nO próximo passo consiste na validação do resumo de alterações para apoiar a elaboração da documentação de aprovação (PPM).",
    "status_updated_at": "17/08/2026 15:53"
  },
  {
    "id": "86ahfj7dm",
    "name": "PRJ Reforma_Tributára_SAP_NFE_NFSe Fase 1",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Jan/2026",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86ahe92c9",
    "name": "[PRJ]-DIMP Atendimento a Fiscalização",
    "status": "T.I TRABALHANDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "Corriqueiramente a Fast Shop é notificada pela Secretaria da Fazenda a prestar informações sobre diferenças identificas entre o arquivo DIMP enviado pelas operadoras de cartão e as notas fiscais emitidas de vendas de mercadorias. O que é a DIMP: A DIMP (Declaração de Informações de Meios de Pagamentos) é uma obrigação acessória digital exigida pelas Secretarias de Fazenda estaduais (Sefaz) desde 2020. Ela reúne informações de todas as transações feitas por cartões (crédito/débito), PIX, e outros meios eletrônicos, enviadas por intermediadores de pagamentos para cruzar com a receita declarada pelas empresas e combater a sonegação fiscal. Exemplo da operação: Quando ocorre uma venda de mercadoria e o cliente efetua o pagamento por meio de pagamento por cartões o PIX (meios eletrônicos), a operadora de cartão consolida todas as operações do mês e envia o documento DIMP. A Sefaz recebe esse arquivo e compara com os documentos emitidos.\nExemplo da comparação: Supondo que ocorra uma venda em loja, o cliente efetue o pagamento por cartão de crédito no valor de 1.500,00. Via de regra, haveria uma emissão da nota de venda subsequente no valor de 1.000,00.\nNo fechamento do mês a operadora de cartão enviará a DIMP com esse documento mencionado no arquivo e seu valor.\nA nota fiscal de venda emitida será declarada no SPED FISCAL na apuração de imposto referente ao mês de emissão. \nO fisco irá pegar o arquivo da DIMP e todas as notas emitidas e comparar se resultará em saldo ZERO.\nSe os valores declarados na DIMP forem os mesmos valores das emissões dos documentos, então não haverá diferenças.\n",
    "ultimo_status": "Sob responsabilidade de Alexander, a iniciativa passa por alinhamento com Medeiros para mitigar o risco de bloqueio da PPM.\nO avanço das atividades aguarda a conclusão dessa validação interna para a desmobilização do potencial impedimento.",
    "status_updated_at": "17/08/2026 11:03"
  },
  {
    "id": "86ah40j3y",
    "name": "[PRJ]-PAGALEVE (Pix Parcelado)",
    "status": "ENVIADO AO REQUISITANTE",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "A integração do Pix Parcelado (PagaLeve) aguarda o posicionamento da área fiscal sobre os requisitos regulatórios que já foram encaminhados.\nA ausência de visibilidade sobre o status desta pendência tributária configura o principal ponto de atenção para o avanço do cronograma.",
    "status_updated_at": "17/08/2026 15:53"
  },
  {
    "id": "86ah3zc5g",
    "name": "[PRJ]-Reestruturar processo de cancelamento NFCe",
    "status": "EM REUNIOES",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "  Objetivo: Reestruturar conceito de chamada de cancelamento ou inutilização das NFCe no Gan.\nEstamos identificando ocorrências em que a NFC-e consta como cancelada no Gan, embora permaneça aprovada/autorizada na Sefaz.\nEssa situação ocorre em razão do atraso na comunicação entre Gan e NDD, o que pode levar o sistema a interpretar incorretamente o status final do documento fiscal. Quando uma NFC-e é emitida, existe um tempo limite para retorno do processamento. Se esse prazo for excedido, o Gan pode acionar automaticamente o cancelamento da NFC-e. No entanto, em determinados casos, a nota já foi autorizada pela Sefaz, gerando divergência entre o status registrado no Gan e a situação real do documento fiscal.\nO impacto dessa falha se reflete em diversas etapas de ajuste interno, entre elas:\n·         Abertura de chamado para que o Gan volte a considerar a NFC-e como ativa.\n·         Ajuste de estoque. Caso esse processo não seja realizado, o saldo permanece incorreto.\n·         Em determinadas situações, o Gan cancela a nota e é realizado um refaturamento. Nesses casos, duas notas ficam autorizadas para o mesmo SKU vendido. Para regularização, torna-se necessário gerar uma DV ficta para neutralizar a venda da NFC-e original, processo que atualmente não faz parte da rotina do time fiscal.\nTodo esse processo consome tempo do time fiscal, embora essa área não seja a responsável por executar ajustes sistêmicos nem por realizar abertura de chamados.\nCaso real: em 04/2026, fomos notificados pela BA em razão de confronto de estoque, no qual foram identificadas divergências entre a movimentação das notas fiscais e a declaração do SPED. Na análise de um dos casos, verificou-se que a nota fiscal estava aprovada na Sefaz, porém permanecia cancelada no Gan. Como o sistema manteve o status incorreto, o estoque final do mês foi fechado com 1 peça a maior. Consequentemente, foi declarado no SPED Fiscal, bloco H, o saldo de 1 peça em estoque, quando o correto seria saldo zero. Considerando o conjunto de SKUs afetados, houve notificação no valor aproximado de R$ 9 mil relacionada a essas ocorrências.\nO aumento dessas ocorrências está relacionado à implementação do projeto que direcionou todas as notas de vendas presenciais para emissão via NFC-e. Como o Estado de São Paulo não estava contemplado originalmente na regra, houve ampliação da exposição a esse tipo de falha.\nPrecisamos efetuar ajuste no Gan + NDD para identificar a falha.\nNa análise realizada, identificamos casos em que a autorização da Sefaz ocorreu cerca de 2 minutos após o envio do pedido de cancelamento, evidenciando a defasagem de comunicação que origina a inconsistência de status.\n    \n",
    "ultimo_status": "O projeto registra como última movimentação o compartilhamento de uma imagem por Sergio Sanchez, sem detalhamento textual de progresso no histórico.\nAguardam-se a definição da justificativa formal e a análise do arquivo enviado para o direcionamento das próximas etapas e alinhamento do escopo.",
    "status_updated_at": "17/08/2026 11:03"
  },
  {
    "id": "86aghx74e",
    "name": "[PRJ]-Melhoria monitor SAP ADDVISOR",
    "status": "AGUARDO INICIO HOMOL",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Propostas comerciais em validação pelo departamento Jurídico (Projuris), restando a definição do cronograma para o avanço do projeto.\nPróxima etapa agendada para 18/08/26 para a apresentação técnica da plataforma Cloud pela Addvisor.",
    "status_updated_at": "15/08/2026 16:29"
  },
  {
    "id": "86afkdv17",
    "name": "[PRJ]-PPM \"Compre Junto\" Brinde/Bonificação",
    "status": "ENVIADO AO REQUISITANTE",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "Aguardando definição sobre o requisito fiscal enviado para a área responsável, cujo status atual e andamento são desconhecidos.\nAdicionalmente, pendente o retorno de Sergio Sanchez sobre a verificação da documentação da PPM e criação de pasta de identificação.",
    "status_updated_at": "17/08/2026 15:53"
  },
  {
    "id": "86af8w8j1",
    "name": "[PRJ:]-CBENEF GAN e SAP",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Abr/2026",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86af3zqga",
    "name": "[PRJ]-Reforma Tributária SAP - Fase 2",
    "status": "T.I TRABALHANDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "Projeto de reforma tributária da Nota Fiscal de Serviço NFS-e. Recebimento de notas de serviço por terceiros. Configurar o SAP para estar preparado para recebimento destes documentos fiscais. Tanto para NFe e NFSe\n",
    "ultimo_status": "Ajustes para emissão de documentos fiscais de transferência (CST e cClassTrib) foram implantados e seguem em homologação com suporte da consultoria ABACO.\nO avanço do projeto depende do posicionamento pendente de Carol Godoy para Alexander referente à validação da proposta da ELO.",
    "status_updated_at": "17/08/2026 15:53"
  },
  {
    "id": "86af3zj95",
    "name": "[PRJ]-Operador Logístico Fase 2 - Cajamar Abastacer",
    "status": "EM REUNIOES",
    "status_ppm": "PPM em Revisão",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "Efetuar abastecimento dos operadores logisticos pela filial Cajamar 1 (63)\n",
    "ultimo_status": "Aguardando definição estratégica referente à potencial criação de um novo e-commerce (CjJ 4).\nAs etapas seguintes do projeto permanecem sem direcionamento conclusivo até a homologação desta decisão.",
    "status_updated_at": "17/08/2026 11:04"
  },
  {
    "id": "86ae5ytkw",
    "name": "[PRJ]-Reforma Tributária SAP - NFe e NFSe - Fase 1",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Jan/2026",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86ae39yjg",
    "name": "[PRJ]:-Atacadistas São Paulo Cajamar",
    "status": "EM REUNIOES",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "Cajamar 1 efetuar venda por Atacado\n",
    "ultimo_status": "A iniciativa para o estabelecimento do novo CNPJ atacadista em Cajamar (SP) permanece sem atualizações de status ou definição de prioridade até o momento.\nO projeto aguarda direcionamento estratégico sobre sua priorização para que as atividades de implantação possam ser iniciadas.",
    "status_updated_at": "17/08/2026 11:04"
  },
  {
    "id": "86ae39wp7",
    "name": "[DMND0002244]-Compra e Ordem em operação com Operador Logistico",
    "status": "ARQUIVADO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86aav1b9d",
    "name": "[PRJ]-Empresa \"FR\" Empresa de Logistica",
    "status": "CONCLUIDO",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "CONCLUIDO",
    "golive": "Ago/2025",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86a88zqpx",
    "name": "[PRJ]-Importação por encomenda 2026",
    "status": "AGUARDO INICIO HOMOL",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": " O objetivo desta demanda é adaptar os sistemas da Fast Shop para atender o processo de venda de produtos importados por encomenda. Com a implantação do processo de venda com exclusividade para estes produtos, os sistemas envolvidos devem ser adaptados para proporcionar o controle sobre o IPI, que deve ser recolhido sempre na primeira movimentação do produto após seu recebimento no Centro de Distribuição (CD) Cajamar 1 – filial , ou seja, só ocorrerá nas saídas de transferências para as Lojas ou CDs, incluído o Cajamar 2 (filial 33)\nO que é importação por encomenda:\nA importação por encomenda ocorre quando uma empresa (encomendante) contrata outra (importadora) para importar bens em seu nome. A importadora compra com seus próprios recursos e revende ao encomendante após o desembaraço aduaneiro.\nFuncionamento: Contrato define termos; importadora compra; realiza o despacho aduaneiro em seu nome; e revende as mercadorias.\nCaracterísticas: A importadora é totalmente responsável e usa seus próprios recursos. A relação é contratual e registrada no Siscomex.\nDiferença da importação por conta e ordem: Na encomenda, a importadora compra e revende com seus recursos; na conta e ordem, a encomendante compra e paga os custos à importadora, que apenas realiza o despacho.\nVantagens: Agilidade, potencial redução de custos e flexibilidade na escolha de fornecedores e condições.\nImportante: Requer registro no Siscomex e habilitação de ambas as empresas no comércio exterior.\nNo processo de importação por encomenda a importadora contratada, após o desembaraço aduaneiro e todos os processos inerentes, emitira uma NFe de venda para a Fast Shop. A partir deste ponto, o processo da Fast Shop seguirá um fluxo comum de entrada de mercadoria.\n",
    "ultimo_status": "A EF foi validada em 20/07/2026 após o ajuste da PPM para 2026 em decorrência da exclusão do IPI do escopo operacional.\nO cronograma do projeto permanece pendente de definição, restando ainda estruturar e incorporar o fluxo para o processo de revenda.",
    "status_updated_at": "17/08/2026 11:04"
  },
  {
    "id": "86a7p7uwv",
    "name": "[PRJ:]-DIMP-Declaração de Informações de Meios de Pagamentos",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Jan/2026",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86a5y9yxg",
    "name": "[PRJ]-ES-Falha destaque ICMS OP venda em indenização (Pacote)",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Jul/2026",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86a3vz587",
    "name": "[PRJ:]-CNPJ Alfanumérico",
    "status": "AGUARDO SUBIDA PRODUCAO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "Ago/2026",
    "prazo": "",
    "ano_ppm": "2024",
    "area": "Fiscal",
    "resumo_raw": "Esta PPM tem como objetivo regulatório atender mudança na regra de criação de CNPJ que passarão ser criados com caracteres alfanuméricos para a Receita Federal ampliar a capacidade de números de CNPJ para abertura de novas empresas devido o esgotamento do modelo atual.\nA Publicação da Nota Técnica 2025.001 Versão 1.00 de 25 de abril de 2025, abrange os ambientes de autorização de documentos fiscais eletrônicos sob a coordenaçãomdo ENCAT: NFe, NFCe, CTe, CTe OS, GTVe, MDFe, BPe, BPe TM, NF3e e NFCom.\nAs adequações dos sistemas se fazem necessário devido o CNPJ ser responsável pela identificação do emitente/destinatário além de compor a chave de acesso do documento fiscal.\nEsta alteração já está prevista na nova estrutura no schema XML conforme nota técnica da Reforma Tributária.\n",
    "ultimo_status": "Implantação reprogramada para 04/08 devido ao congelamento de julho, exigindo a finalização dos testes integrados até 24/07 e aprovação no CAB em 29/07.\nA frente SAP ECC aguarda correção de chamado pelo Mercado Eletrônico para prosseguir com os cenários, enquanto a frente AddTax possui testes agendados para 13/07.",
    "status_updated_at": "17/08/2026 11:04"
  },
  {
    "id": "86a359uda",
    "name": "[PRJ:]-Destacar ICMS PRÓPRIO FL 63 para Fl 05 (Pacote)",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Jun/2026",
    "prazo": "",
    "ano_ppm": "2024",
    "area": "Fiscal",
    "resumo_raw": "Na operação de transferência entre 63 e 05, não está sendo destacado o ICMS ST.\nFoi identificado uma falha na regra. Inicialmente foi aberto um chamado que será usado para montar a PPM.\n\nO Impacto é a falta de recolhimento de Imposto. Precisamos ajustar o quanto antes.\n\n\n",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86a30xwra",
    "name": "[PRJ]-Operação de Cessão de Crédito (Credix) e (TradeMaster)",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Abr/2026",
    "prazo": "",
    "ano_ppm": "2024",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "864ee7nrp",
    "name": "[PRJ:]-Fullfilment Amazon (FBA)",
    "status": "EM HOMOLOGACAO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "Jul/2026",
    "prazo": "",
    "ano_ppm": "2023",
    "area": "Terceiros",
    "resumo_raw": " A adoção do modelo de Fulfillment no marketplace Amazon (FBA) consiste no envio de parte do estoque da Fast Shop para os centros de distribuição da Amazon, que passa a ser responsável por toda a operação logística — incluindo armazenamento, separação, expedição, entrega, atendimento ao cliente (SAC logístico) e logística reversa.\nEsse modelo potencializa a competitividade ao proporcionar melhores níveis de serviço (SLA), elegibilidade ao programa Prime, aumento da taxa de conversão nas vitrines e fortalecimento da reputação nas plataformas, além de possibilitar ganhos de eficiência operacional e otimização de custos logísticos. A adoção do modelo FBA visa ganho de competitividade (Prime, SLA, conversão), porém o modelo atual apresenta inviabilidade tributária no cenário SP (CJ63 → CJ05), exigindo revisão da malha logística e do modelo fiscal para viabilização econômica. Diante disso, foi aprovada a utilização de Santa Catarina (SC) como centro consolidador logístico, com o objetivo de viabilizar economicamente o modelo FBA.\n    \n",
    "ultimo_status": "A homologação do fluxo FBA está temporariamente suspensa devido a divergências cadastrais e alterações unilaterais nos processos de transferência da Amazon.\nA equipe de projeto atua na implementação de medidas corretivas junto ao parceiro para mitigar os impactos e viabilizar a retomada dos testes.",
    "status_updated_at": "17/08/2026 15:53"
  },
  {
    "id": "864e98d8y",
    "name": "[PRJ:]-Projeto X3 Atacadista Revenda",
    "status": "AGUARDO INICIO HOMOL",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "Ago/2026",
    "prazo": "",
    "ano_ppm": "2023",
    "area": "Fiscal",
    "resumo_raw": "Permitir que a Filial X3 Atacadista efetue vendas para revenda.\nAtualmente apenas efetua transferência.\n\n",
    "ultimo_status": "Conclusão da PPM e definição das regras fiscais de ICMS para mitigar riscos em operações internas de uso e consumo.\nPróximo passo consiste na validação do documento de especificação técnica EF_DMND0002001_v1.1, entregue para revisão.",
    "status_updated_at": ""
  },
  {
    "id": "3d3hxfr",
    "name": "[PRJ]-Substituição do Mastersaf-DW (TaxOne)",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Abr/2026",
    "prazo": "",
    "ano_ppm": "2023",
    "area": "Fiscal",
    "resumo_raw": "Data fim de atualização do MSAF 31/12/2025. Após isso não teremos mais atualizações\nno MSAF DW. Sendo necessário migrar para TAXOne. \nEm conversar com o Marcio TI, a definição/decisão de continuar ou não com MSAF\nserá dele.\n\n",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  }
];

const resumosMap = {
  "[PRJ}-Criação Chamados na plataforma HALO (Portal Fast)": "As áreas Tributária, Fiscal e Paralegal recebem diversas demandas de outros departamentos internos na Fast Shop com a necessidade de realizar ajustes em sistema, regularizações jurídicas, ajustes para liberações de documentos Fiscais, além rastreabilidade e eficiência dos atendimentos destes pedidos, podendo ser registrados em um único ambiente, garantindo maior controle dos prazos, definição de responsabilidades, histórico centralizado das interações e melhor visibilidade sobre o volume e status dos atendimentos.\nO portal reduzirá riscos de perda das informações com uma melhora de governança nos processos, facilitando a geração de indicadores de desempenho e proporcionando uma experiência mais ágil e transparente tanto para o solicitante quanto para a equipe fiscal.\n    \n",
  "[PRJ:DMND2148]-Reforma Tributária Devolução FinNfe= 4 DfeReferencia": "Com a reforma tributária são necessários ajustes nos processos de emissão de Notas Fiscais Eletrônicas. \nDe acordo com a publicação da NT_2025.002_v1.50, será necessário antecipar algumas funcionalidades previstas na PPM da Reforma Tributária em desenvolvimento, que passará a vigorar em ambiente de produção a partir de 05/10/2026. Uma delas é o referenciamento de chave origem a nível de item. Se não ocorrer a implementação as notas serão rejeitadas.\n    \n",
  "[PRJ]-Venda com entrega em Operador Logístico": "A implementação do processo de Venda com entrega em Operador Logístico representa uma evolução estratégica para o canal B2B, ampliando significativamente a capacidade comercial da empresa sem a necessidade de aumento proporcional dos estoques ou da complexidade logística. Esse modelo permite que a empresa atue como fornecedora de mercadorias para parceiros comerciais que solicitam entrega diretamente em operadores logísticos como a operação Full do Mercado Livre e Amazon. Além de expandir o alcance comercial e possibilitar novos modelos de parceria, essa operação simplifica a operação logística da cadeia de suprimento, diminuindo custos de movimentação e armazenamento. Por se tratar de uma operação com requisitos fiscais e logísticos específicos, sua implantação exige a adequação de processos, sistemas e controles internos, garantindo conformidade tributária, rastreabilidade das operações e escalabilidade para suportar o crescimento futuro do canal B2B. \nBenefícios Esperados:\n• Expansão do alcance comercial; \n• Aumento do faturamento B2B sem ampliação relevante da estrutura;\n• Criação de novos modelos de negócio; \n• Maior competitividade e velocidade de atendimento. \n",
  "[PRJ]-T-CIOT, NSTECH, PEF, MDF-e e CT-e": "A ANTT vem ampliando os requisitos de controle das operações de transporte, desde maio de 2026 passou a exigir a emissão de: CIOT, PEF, MDF-e, e CT-e. O não atendimento dessas exigências pode ocasionar em autuações e multas. (R$252K/dia ou R$5.5MM/mês), porém a empresa não possui solução para emissão dos documentos, correndo risco de autuação.\nConsiderando o volume de operação da companhia, e a necessidade de garantir a conformidade legal e eficiência operacional, torna-se necessária a implantação de uma solução para automatizar e gerenciar, os documentos obrigatórios de transporte. Implantar uma plataforma que venha a atender as normativas vigentes e realizando automatização do processo.\n1.1 PROCESSO AS IS\nO processo de contratação e pagamento de fretes, consiste na gestão operacional e financeira, desde o envio da roteirização e execução das entregas, feito pelas transportadoras até o fechamento semanal dos valores de frete. As informações operacionais são consolidadas e validadas para cálculo dos pagamentos, permitindo a emissão de CT-es e faturas pelas transportadoras, porém no processo realizado hoje as transportadoras TAC EQUIPARADO: Não emite o MDFe por falta do CIOT e as transportadoras com mais de 3 veículos não possuem estrutura para emitir as documentações exigidas pela ANTT antes do carregamento. Após isso, o time de fretes analisa a conformidade dos documentos, aprovando-os para liquidação financeira ou encaminhando-os para ajustes quando são identificadas inconsistências. E o pagamento do frete é realizado para todas as transportadoras seja TAC equiparado e transportadoras com mais de 3 veículos via deposito em conta (TED) semanal, sendo que seria necessário para TAC EQUIPARADO pagamento via PEF\n",
  "[PRJ]-Crédito Extemporâneo PISCOFINS - Legado": "Geração de documentação solicitada pela EY para efetuar a refificação da EFD Contribuição de diversos periodos. Foi solicitado bases de contas contábeis, extraidas pelo SAP (Razão das contas contábeis em estrutura analitica).\n",
  "[PRJ]-Exclusão do ICMS ST Antecipação nas Lojas de SP (Sangria 2)": " A Diretoria Fiscal solicitou a criação de uma PPM para implementar a funcionalidade de não calcular o ICMS-ST nas remessas destinadas às lojas do Estado de São Paulo, quando a operação tiver origem na filial ES-Atacadista.\nAS IS\nAtualmente, em uma remessa de transferência da filial ES-Atacadista para qualquer loja localizada no Estado de São Paulo, há obrigatoriedade de recolhimento do ICMS-ST, seja por destaque na nota fiscal, seja por recolhimento na entrada da mercadoria no recebimento. Como não há protocolo firmado entre os Estados do Espírito Santo e de São Paulo, o recolhimento ocorre, em 100% dos casos, na entrada. Esse recolhimento aumenta o custo da mercadoria e impacta o fluxo de caixa. Posteriormente, a venda da mercadoria ocorre sem tributação de ICMS, uma vez que o recolhimento já foi realizado anteriormente.\nTO BE\nO objetivo do projeto é permitir que o sistema interprete essa operação como produto sem regra de ICMS-ST, sem a necessidade de remover ou alterar as regras tributárias dos produtos nos cadastros fiscais.\nEm junho de 2023, foi homologado o projeto “Sangria”, que realiza esse mesmo processo.\nNa ocasião, foram criadas telas de parametrização para vincular as filiais de origem e destino abrangidas pela funcionalidade. Essas telas foram desenvolvidas de forma parametrizável, permitindo novos cadastros conforme a necessidade dos usuários, sem configuração fixa em código. O projeto foi homologado e disponibilizado em produção; porém, em razão de alteração na malha fiscal, acabou não sendo utilizado.\nDessa forma, a presente solicitação já se encontra aproximadamente 80% concluída, restando apenas:\n·         Retestar integralmente o projeto para confirmar se a funcionalidade está 100% utilizável.\n·         Considerar um novo requisito para bloquear a transferência de mercadorias da filial 0063 e Filial 05 para as lojas, para os produtos cadastrados como “Sangria”.\n",
  "[PRJ]-Transportadora FSL Fast Shop Logistic": "Criação de uma Filial Logistica (Emissão de CTe)\n",
  "[PRJ:]-Reforma Tributária - NFSe Nacional GAN Fase 2": "Projeto de reforma tributária da Nota Fiscal de Serviço NFS-e. Atendimento para destacar IBS e CBS na nota fiscal. emissão dos documentos.\n\n",
  "[PRJ]-DIMP Atendimento a Fiscalização": "Corriqueiramente a Fast Shop é notificada pela Secretaria da Fazenda a prestar informações sobre diferenças identificas entre o arquivo DIMP enviado pelas operadoras de cartão e as notas fiscais emitidas de vendas de mercadorias. O que é a DIMP: A DIMP (Declaração de Informações de Meios de Pagamentos) é uma obrigação acessória digital exigida pelas Secretarias de Fazenda estaduais (Sefaz) desde 2020. Ela reúne informações de todas as transações feitas por cartões (crédito/débito), PIX, e outros meios eletrônicos, enviadas por intermediadores de pagamentos para cruzar com a receita declarada pelas empresas e combater a sonegação fiscal. Exemplo da operação: Quando ocorre uma venda de mercadoria e o cliente efetua o pagamento por meio de pagamento por cartões o PIX (meios eletrônicos), a operadora de cartão consolida todas as operações do mês e envia o documento DIMP. A Sefaz recebe esse arquivo e compara com os documentos emitidos.\nExemplo da comparação: Supondo que ocorra uma venda em loja, o cliente efetue o pagamento por cartão de crédito no valor de 1.500,00. Via de regra, haveria uma emissão da nota de venda subsequente no valor de 1.000,00.\nNo fechamento do mês a operadora de cartão enviará a DIMP com esse documento mencionado no arquivo e seu valor.\nA nota fiscal de venda emitida será declarada no SPED FISCAL na apuração de imposto referente ao mês de emissão. \nO fisco irá pegar o arquivo da DIMP e todas as notas emitidas e comparar se resultará em saldo ZERO.\nSe os valores declarados na DIMP forem os mesmos valores das emissões dos documentos, então não haverá diferenças.\n",
  "[PRJ]-Reestruturar processo de cancelamento NFCe": "  Objetivo: Reestruturar conceito de chamada de cancelamento ou inutilização das NFCe no Gan.\nEstamos identificando ocorrências em que a NFC-e consta como cancelada no Gan, embora permaneça aprovada/autorizada na Sefaz.\nEssa situação ocorre em razão do atraso na comunicação entre Gan e NDD, o que pode levar o sistema a interpretar incorretamente o status final do documento fiscal. Quando uma NFC-e é emitida, existe um tempo limite para retorno do processamento. Se esse prazo for excedido, o Gan pode acionar automaticamente o cancelamento da NFC-e. No entanto, em determinados casos, a nota já foi autorizada pela Sefaz, gerando divergência entre o status registrado no Gan e a situação real do documento fiscal.\nO impacto dessa falha se reflete em diversas etapas de ajuste interno, entre elas:\n·         Abertura de chamado para que o Gan volte a considerar a NFC-e como ativa.\n·         Ajuste de estoque. Caso esse processo não seja realizado, o saldo permanece incorreto.\n·         Em determinadas situações, o Gan cancela a nota e é realizado um refaturamento. Nesses casos, duas notas ficam autorizadas para o mesmo SKU vendido. Para regularização, torna-se necessário gerar uma DV ficta para neutralizar a venda da NFC-e original, processo que atualmente não faz parte da rotina do time fiscal.\nTodo esse processo consome tempo do time fiscal, embora essa área não seja a responsável por executar ajustes sistêmicos nem por realizar abertura de chamados.\nCaso real: em 04/2026, fomos notificados pela BA em razão de confronto de estoque, no qual foram identificadas divergências entre a movimentação das notas fiscais e a declaração do SPED. Na análise de um dos casos, verificou-se que a nota fiscal estava aprovada na Sefaz, porém permanecia cancelada no Gan. Como o sistema manteve o status incorreto, o estoque final do mês foi fechado com 1 peça a maior. Consequentemente, foi declarado no SPED Fiscal, bloco H, o saldo de 1 peça em estoque, quando o correto seria saldo zero. Considerando o conjunto de SKUs afetados, houve notificação no valor aproximado de R$ 9 mil relacionada a essas ocorrências.\nO aumento dessas ocorrências está relacionado à implementação do projeto que direcionou todas as notas de vendas presenciais para emissão via NFC-e. Como o Estado de São Paulo não estava contemplado originalmente na regra, houve ampliação da exposição a esse tipo de falha.\nPrecisamos efetuar ajuste no Gan + NDD para identificar a falha.\nNa análise realizada, identificamos casos em que a autorização da Sefaz ocorreu cerca de 2 minutos após o envio do pedido de cancelamento, evidenciando a defasagem de comunicação que origina a inconsistência de status.\n    \n",
  "[PRJ]-Reforma Tributária SAP - Fase 2": "Projeto de reforma tributária da Nota Fiscal de Serviço NFS-e. Recebimento de notas de serviço por terceiros. Configurar o SAP para estar preparado para recebimento destes documentos fiscais. Tanto para NFe e NFSe\n",
  "[PRJ]-Operador Logístico Fase 2 - Cajamar Abastacer": "Efetuar abastecimento dos operadores logisticos pela filial Cajamar 1 (63)\n",
  "[PRJ]:-Atacadistas São Paulo Cajamar": "Cajamar 1 efetuar venda por Atacado\n",
  "[PRJ]-Importação por encomenda 2026": " O objetivo desta demanda é adaptar os sistemas da Fast Shop para atender o processo de venda de produtos importados por encomenda. Com a implantação do processo de venda com exclusividade para estes produtos, os sistemas envolvidos devem ser adaptados para proporcionar o controle sobre o IPI, que deve ser recolhido sempre na primeira movimentação do produto após seu recebimento no Centro de Distribuição (CD) Cajamar 1 – filial , ou seja, só ocorrerá nas saídas de transferências para as Lojas ou CDs, incluído o Cajamar 2 (filial 33)\nO que é importação por encomenda:\nA importação por encomenda ocorre quando uma empresa (encomendante) contrata outra (importadora) para importar bens em seu nome. A importadora compra com seus próprios recursos e revende ao encomendante após o desembaraço aduaneiro.\nFuncionamento: Contrato define termos; importadora compra; realiza o despacho aduaneiro em seu nome; e revende as mercadorias.\nCaracterísticas: A importadora é totalmente responsável e usa seus próprios recursos. A relação é contratual e registrada no Siscomex.\nDiferença da importação por conta e ordem: Na encomenda, a importadora compra e revende com seus recursos; na conta e ordem, a encomendante compra e paga os custos à importadora, que apenas realiza o despacho.\nVantagens: Agilidade, potencial redução de custos e flexibilidade na escolha de fornecedores e condições.\nImportante: Requer registro no Siscomex e habilitação de ambas as empresas no comércio exterior.\nNo processo de importação por encomenda a importadora contratada, após o desembaraço aduaneiro e todos os processos inerentes, emitira uma NFe de venda para a Fast Shop. A partir deste ponto, o processo da Fast Shop seguirá um fluxo comum de entrada de mercadoria.\n",
  "[PRJ:]-CNPJ Alfanumérico": "Esta PPM tem como objetivo regulatório atender mudança na regra de criação de CNPJ que passarão ser criados com caracteres alfanuméricos para a Receita Federal ampliar a capacidade de números de CNPJ para abertura de novas empresas devido o esgotamento do modelo atual.\nA Publicação da Nota Técnica 2025.001 Versão 1.00 de 25 de abril de 2025, abrange os ambientes de autorização de documentos fiscais eletrônicos sob a coordenaçãomdo ENCAT: NFe, NFCe, CTe, CTe OS, GTVe, MDFe, BPe, BPe TM, NF3e e NFCom.\nAs adequações dos sistemas se fazem necessário devido o CNPJ ser responsável pela identificação do emitente/destinatário além de compor a chave de acesso do documento fiscal.\nEsta alteração já está prevista na nova estrutura no schema XML conforme nota técnica da Reforma Tributária.\n",
  "[PRJ:]-Destacar ICMS PRÓPRIO FL 63 para Fl 05 (Pacote)": "Na operação de transferência entre 63 e 05, não está sendo destacado o ICMS ST.\nFoi identificado uma falha na regra. Inicialmente foi aberto um chamado que será usado para montar a PPM.\n\nO Impacto é a falta de recolhimento de Imposto. Precisamos ajustar o quanto antes.\n\n\n",
  "[PRJ:]-Fullfilment Amazon (FBA)": " A adoção do modelo de Fulfillment no marketplace Amazon (FBA) consiste no envio de parte do estoque da Fast Shop para os centros de distribuição da Amazon, que passa a ser responsável por toda a operação logística — incluindo armazenamento, separação, expedição, entrega, atendimento ao cliente (SAC logístico) e logística reversa.\nEsse modelo potencializa a competitividade ao proporcionar melhores níveis de serviço (SLA), elegibilidade ao programa Prime, aumento da taxa de conversão nas vitrines e fortalecimento da reputação nas plataformas, além de possibilitar ganhos de eficiência operacional e otimização de custos logísticos. A adoção do modelo FBA visa ganho de competitividade (Prime, SLA, conversão), porém o modelo atual apresenta inviabilidade tributária no cenário SP (CJ63 → CJ05), exigindo revisão da malha logística e do modelo fiscal para viabilização econômica. Diante disso, foi aprovada a utilização de Santa Catarina (SC) como centro consolidador logístico, com o objetivo de viabilizar economicamente o modelo FBA.\n    \n",
  "[PRJ:]-Projeto X3 Atacadista Revenda": "Permitir que a Filial X3 Atacadista efetue vendas para revenda.\nAtualmente apenas efetua transferência.\n\n",
  "[PRJ]-Substituição do Mastersaf-DW (TaxOne)": "Data fim de atualização do MSAF 31/12/2025. Após isso não teremos mais atualizações\nno MSAF DW. Sendo necessário migrar para TAXOne. \nEm conversar com o Marcio TI, a definição/decisão de continuar ou não com MSAF\nserá dele.\n\n"
};
