// Gerado automaticamente via ClickUp API + Gemini em 15/08/2026 17:02:47
const lastUpdate = '15/08/2026 17:02:47';
const rawData = [
  {
    "id": "86ajqc9ph",
    "name": "[PRJ}-Criação Chamados na plataforma HALO (Portal Fast)",
    "status": "CRIANDO PPM",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "As áreas Tributária, Fiscal e Paralegal recebem diversas demandas de outros departamentos internos na Fast Shop com a necessidade de realizar ajustes em sistema, regularizações jurídicas, ajustes para liberações de documentos Fiscais, além rastreabilidade e eficiência dos atendimentos destes pedidos, podendo ser registrados em um único ambiente, garantindo maior controle dos prazos, definição de responsabilidades, histórico centralizado das interações e melhor visibilidade sobre o volume e status dos atendimentos.\nO portal reduzirá riscos de perda das informações com uma melhora de governança nos processos, facilitando a geração de indicadores de desempenho e proporcionando uma experiência mais ágil e transparente tanto para o solicitante quanto para a equipe fiscal.\n    \n",
    "ultimo_status": "Solicitada a elaboração do Documento Técnico (TD) para estruturação do fluxo de chamados fiscais e paralegais na plataforma HALO.\nO próximo passo consiste no desenho da solução para centralizar as demandas de e-mails e do sistema FCchamados, visando gerar indicadores da área.",
    "status_updated_at": "15/08/2026 17:00"
  },
  {
    "id": "86ajp65xa",
    "name": "[PRJ:DMND2148]-Reforma Tributária Devolução FinNfe= 4 DfeReferencia",
    "status": "EM HOMOLOGACAO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "Ago/2026",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Demanda liberada para testes com evidências validadas, aguardando o início da homologação sob responsabilidade da analista Ellen.\nO cronograma oficial prevê homologação entre 10 e 14/08/2026, aprovação no CAB em 19/08 e Go-Live agendado para 25/08/2026.",
    "status_updated_at": "15/08/2026 17:00"
  },
  {
    "id": "86ajnr5t7",
    "name": "[PRJ]-Triangulação de Vendas",
    "status": "EM REUNIOES",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "Sem registros de justificativa, histórico de interações ou progresso documentados para a iniciativa até o momento.\nRecomenda-se a definição imediata do escopo estrutural e o alinhamento com os stakeholders para a realização do kick-off.",
    "status_updated_at": "03/08/2026 17:14"
  },
  {
    "id": "86ajn2bf9",
    "name": "[PRJ]- Migração para modelo de Split de Pagamento no Marketplace",
    "status": "EM REUNIOES",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "A validação jurídica preliminar das minutas contratuais foi concluída, restando a análise de impactos regulatórios e tributários pelo time Fiscal.\nEsta avaliação pelo setor Fiscal está programada para iniciar após o fechamento mensal em 13/07, concomitante ao registro formal do projeto no portfólio.",
    "status_updated_at": "03/08/2026 17:14"
  },
  {
    "id": "86ajn2519",
    "name": "[PRJ]-Venda produto Rua Q e Rua P",
    "status": "EM REUNIOES",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "Atividades atualmente suspensas devido à pendência de esclarecimentos cruciais por parte de Murata sobre as diretrizes do escopo.\nAguarda-se este alinhamento técnico para o desbloqueio das próximas etapas de execução e avanço da equipe.",
    "status_updated_at": "03/08/2026 17:14"
  },
  {
    "id": "86ajn24ga",
    "name": "[PRJ]-Venda de Sucata 63",
    "status": "EM REUNIOES",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "Fase de inicialização sem registro de interações ou detalhamento de justificativa no sistema até o momento.\nAguardam-se as definições preliminares de escopo e o alinhamento da equipe para o início das atividades.",
    "status_updated_at": "15/08/2026 16:28"
  },
  {
    "id": "86ajmpzkk",
    "name": "[PRJ]-Venda com entrega em Operador Logístico",
    "status": "ENVIADO AO REQUISITANTE",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "07/2026",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "A proposta de projeto (PPM) contendo as considerações operacionais e os requisitos fiscais foi enviada ao requisitante em 27/07/2026.\nA iniciativa aguarda a validação do solicitante para o direcionamento dos próximos passos e início das adequações sistêmicas.",
    "status_updated_at": ""
  },
  {
    "id": "86ajd31ab",
    "name": "[PRJ]-T-CIOT, NSTECH, PEF, MDF-e e CT-e",
    "status": "EM REUNIOES",
    "status_ppm": "PPM em Andamento",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "Disponibilizada a versão 7 do planejamento PPM CIOT (julho/2026), avançando na estruturação do processo de conformidade regulatória.\nO foco prioritário é a implantação célere da plataforma de automação de documentos de transporte para mitigar o passivo de multas diárias junto à ANTT.",
    "status_updated_at": "03/08/2026 17:15"
  },
  {
    "id": "86ajc7q9w",
    "name": "[PRJ]-Crédito Extemporâneo PISCOFINS - Legado",
    "status": "T.I TRABALHANDO",
    "status_ppm": "Sem PPM",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "A base do SAP foi extraída pela TI e disponibilizada no Databricks, aguardando o download pela responsável.\nA próxima ação consiste no envio deste arquivo para a EY para dar continuidade às atividades.",
    "status_updated_at": "15/08/2026 16:30"
  },
  {
    "id": "86ajc7hu3",
    "name": "[PRJ]-Exclusão do ICMS ST Antecipação nas Lojas de SP (Sangria 2)",
    "status": "AGUARDO SUBIDA PRODUCAO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "Ago/2026",
    "prazo": "07/2026",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "A homologação e os testes sistêmicos encontram-se suspensos aguardando parecer jurídico sobre a coexistência tributária e a definição do CNPJ da Dark Store de Cajamar.\nA área de TI estima duas semanas de esforço para desenvolvimento e retestes assim que sanadas as pendências fiscais e regulatórias do projeto.",
    "status_updated_at": "15/08/2026 16:28"
  },
  {
    "id": "86ahw2uge",
    "name": "[PRJ]-Transportadora FSL Fast Shop Logistic",
    "status": "EM REUNIOES",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "Com o Business Case e a documentação preliminar estruturados, a área responsável realiza o estudo de viabilidade sistêmica para a emissão de CTe em todos os processos.\nA modelagem operacional em avaliação assemelha-se ao formato FBA e prevê a utilização de certificado digital próprio para viabilizar as transações.",
    "status_updated_at": "03/08/2026 17:15"
  },
  {
    "id": "86ahfje7y",
    "name": "[PRJ:]-Reforma Tributária - NFSe Nacional GAN Fase 2",
    "status": "T.I TRABALHANDO",
    "status_ppm": "PPM em Andamento",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Apresentada a tela de simulação de serviço e recebido o alinhamento dos ajustes acordados com a Neogrid para aprovação.\nO andamento atual foca na validação desse resumo de ajustes para subsidiar a estruturação da proposta do projeto (PPM).",
    "status_updated_at": ""
  },
  {
    "id": "86ahfj7dm",
    "name": "PRJ Reforma_Tributára_SAP_NFE_NFSe Fase 1",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Jan/2026",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86ahe92c9",
    "name": "[PRJ]-DIMP Atendimento a Fiscalização",
    "status": "T.I TRABALHANDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Tratativa em andamento conduzida por Alexander junto a Medeiros para evitar o potencial bloqueio da PPM.\nA continuidade das atividades do projeto depende da resolução deste alinhamento interno pendente.",
    "status_updated_at": ""
  },
  {
    "id": "86ah3zc5g",
    "name": "[PRJ]-Reestruturar processo de cancelamento NFCe",
    "status": "EM REUNIOES",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Alinhamento da reestruturação iniciado com o envio de insumo visual por Sergio Sanchez, sem impedimentos registrados.\nAguardam-se o detalhamento do escopo e a definição formal das próximas etapas para dar sequência ao cronograma de entregas.",
    "status_updated_at": "15/08/2026 16:28"
  },
  {
    "id": "86aghx74e",
    "name": "[PRJ]-Melhoria monitor SAP ADDVISOR",
    "status": "AGUARDO INICIO HOMOL",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Propostas comerciais em validação pelo departamento Jurídico (Projuris), restando a definição do cronograma para o avanço do projeto.\nPróxima etapa agendada para 18/08/26 para a apresentação técnica da plataforma Cloud pela Addvisor.",
    "status_updated_at": "15/08/2026 16:29"
  },
  {
    "id": "86af8w8j1",
    "name": "[PRJ:]-CBENEF GAN e SAP",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Abr/2026",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86af3zqga",
    "name": "[PRJ]-Reforma Tributária SAP - Fase 2",
    "status": "T.I TRABALHANDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Ajustes para emissão de documentos fiscais de transferências (CST e cClassTrib) foram implantados no ambiente de homologação.\nPendente o retorno de Carol Godoy a Alexander referente à validação e acordo sobre a proposta comercial da ELO.",
    "status_updated_at": ""
  },
  {
    "id": "86af3zj95",
    "name": "[PRJ]-Operador Logístico Fase 2 - Cajamar Abastacer",
    "status": "EM REUNIOES",
    "status_ppm": "PPM em Revisão",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Definição estratégica sobre a criação de um novo e-commerce (CjJ 4) segue pendente, impactando o direcionamento das próximas etapas do projeto.\nAtualmente, as atividades aguardam posicionamento oficial da liderança para a retomada do planejamento e detalhamento técnico.",
    "status_updated_at": ""
  },
  {
    "id": "86ae5ytkw",
    "name": "[PRJ]-Reforma Tributária SAP - NFe e NFSe - Fase 1",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Jan/2026",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86ae39yjg",
    "name": "[PRJ]:-Atacadistas São Paulo Cajamar",
    "status": "EM REUNIOES",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "A FAZER",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "A criação do novo CNPJ com CNAE de Atacadista em Cajamar (SP) encontra-se em aguardo de definição de priorização corporativa.\nAté o momento, não há atualizações recentes sobre o andamento da demanda ou direcionamentos para o início das próximas etapas.",
    "status_updated_at": "03/08/2026 17:16"
  },
  {
    "id": "86ae39wp7",
    "name": "[DMND0002244]-Compra e Ordem em operação com Operador Logistico",
    "status": "ARQUIVADO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2026",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86aav1b9d",
    "name": "[PRJ]-Empresa \"FR\" Empresa de Logistica",
    "status": "CONCLUIDO",
    "status_ppm": "PPM não iniciada",
    "kanban_status": "CONCLUIDO",
    "golive": "Ago/2025",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86a88zqpx",
    "name": "[PRJ]-Importação por encomenda 2026",
    "status": "AGUARDO INICIO HOMOL",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "",
    "status_updated_at": ""
  },
  {
    "id": "86a7p7uwv",
    "name": "[PRJ:]-DIMP-Declaração de Informações de Meios de Pagamentos",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Jan/2026",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86a5y9yxg",
    "name": "[PRJ]-ES-Falha destaque ICMS OP venda em indenização (Pacote)",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Jul/2026",
    "prazo": "",
    "ano_ppm": "2025",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86a3vz587",
    "name": "[PRJ:]-CNPJ Alfanumérico",
    "status": "AGUARDO SUBIDA PRODUCAO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "Ago/2026",
    "prazo": "",
    "ano_ppm": "2024",
    "area": "Fiscal",
    "resumo_raw": "",
    "ultimo_status": "Implantação reprogramada para 04/08 devido ao congelamento de TI, exigindo finalização das homologações de SAP ECC e AddTax até 24/07 para aprovação no CAB em 29/07.\nA frente SAP ECC aguarda resolução de chamado de inconsistência no Mercado Eletrônico, enquanto os testes do AddTax estão agendados para o dia 13/07.",
    "status_updated_at": ""
  },
  {
    "id": "86a359uda",
    "name": "[PRJ:]-Destacar ICMS PRÓPRIO FL 63 para Fl 05 (Pacote)",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Jun/2026",
    "prazo": "",
    "ano_ppm": "2024",
    "area": "Fiscal",
    "resumo_raw": "Na operação de transferência entre 63 e 05, não está sendo destacado o ICMS ST.\nFoi identificado uma falha na regra. Inicialmente foi aberto um chamado que será usado para montar a PPM.\n\nO Impacto é a falta de recolhimento de Imposto. Precisamos ajustar o quanto antes.\n\n\n",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "86a30xwra",
    "name": "[PRJ]-Operação de Cessão de Crédito (Credix) e (TradeMaster)",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Abr/2026",
    "prazo": "",
    "ano_ppm": "2024",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  },
  {
    "id": "864ee7nrp",
    "name": "[PRJ:]-Fullfilment Amazon (FBA)",
    "status": "EM HOMOLOGACAO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "Jul/2026",
    "prazo": "",
    "ano_ppm": "2023",
    "area": "Terceiros",
    "resumo_raw": "",
    "ultimo_status": "Homologação suspensa devido a alterações nos processos de transferências e divergências nos dados cadastrais dos centros de distribuição da Amazon.\nMedidas corretivas estão sendo adotadas junto ao parceiro para mitigar as inconsistências e viabilizar o reinício dos testes de validação.",
    "status_updated_at": "15/08/2026 17:02"
  },
  {
    "id": "864e98d8y",
    "name": "[PRJ:]-Projeto X3 Atacadista Revenda",
    "status": "AGUARDO INICIO HOMOL",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "EM ANDAMENTO",
    "golive": "Ago/2026",
    "prazo": "",
    "ano_ppm": "2023",
    "area": "Fiscal",
    "resumo_raw": "Permitir que a Filial X3 Atacadista efetue vendas para revenda.\nAtualmente apenas efetua transferência.\n\n",
    "ultimo_status": "Conclusão da PPM e definição das regras fiscais de ICMS para mitigar riscos em operações internas de uso e consumo.\nPróximo passo consiste na validação do documento de especificação técnica EF_DMND0002001_v1.1, entregue para revisão.",
    "status_updated_at": ""
  },
  {
    "id": "3d3hxfr",
    "name": "[PRJ]-Substituição do Mastersaf-DW (TaxOne)",
    "status": "CONCLUIDO",
    "status_ppm": "PPM Finalizada - Está no portal",
    "kanban_status": "CONCLUIDO",
    "golive": "Abr/2026",
    "prazo": "",
    "ano_ppm": "2023",
    "area": "Fiscal",
    "resumo_raw": "Data fim de atualização do MSAF 31/12/2025. Após isso não teremos mais atualizações\nno MSAF DW. Sendo necessário migrar para TAXOne. \nEm conversar com o Marcio TI, a definição/decisão de continuar ou não com MSAF\nserá dele.\n\n",
    "ultimo_status": "Concluido",
    "status_updated_at": ""
  }
];

const resumosMap = {
  "[PRJ}-Criação Chamados na plataforma HALO (Portal Fast)": "As áreas Tributária, Fiscal e Paralegal recebem diversas demandas de outros departamentos internos na Fast Shop com a necessidade de realizar ajustes em sistema, regularizações jurídicas, ajustes para liberações de documentos Fiscais, além rastreabilidade e eficiência dos atendimentos destes pedidos, podendo ser registrados em um único ambiente, garantindo maior controle dos prazos, definição de responsabilidades, histórico centralizado das interações e melhor visibilidade sobre o volume e status dos atendimentos.\nO portal reduzirá riscos de perda das informações com uma melhora de governança nos processos, facilitando a geração de indicadores de desempenho e proporcionando uma experiência mais ágil e transparente tanto para o solicitante quanto para a equipe fiscal.\n    \n",
  "[PRJ:]-Destacar ICMS PRÓPRIO FL 63 para Fl 05 (Pacote)": "Na operação de transferência entre 63 e 05, não está sendo destacado o ICMS ST.\nFoi identificado uma falha na regra. Inicialmente foi aberto um chamado que será usado para montar a PPM.\n\nO Impacto é a falta de recolhimento de Imposto. Precisamos ajustar o quanto antes.\n\n\n",
  "[PRJ:]-Projeto X3 Atacadista Revenda": "Permitir que a Filial X3 Atacadista efetue vendas para revenda.\nAtualmente apenas efetua transferência.\n\n",
  "[PRJ]-Substituição do Mastersaf-DW (TaxOne)": "Data fim de atualização do MSAF 31/12/2025. Após isso não teremos mais atualizações\nno MSAF DW. Sendo necessário migrar para TAXOne. \nEm conversar com o Marcio TI, a definição/decisão de continuar ou não com MSAF\nserá dele.\n\n"
};
